config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :categories
  get 'cart_items/create'

  get 'cart_items/update'

  get 'cart_items/destroy'

  get 'carts/show'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :users
  resources :products do
  resources :orders, only: [:new, :create]
  end
 resource :shopping_cart

  get 'pages/about'
  get 'seller' => "products#seller"
  get 'pages/contact'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

#  if Rails.env.development?
  #      has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "missingimage.png"
 #       validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
 #       #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
 #   else
        require 'aws-sdk-v1'
        require 'aws-sdk'
        has_attached_file :image, styles: { medium: "200x200", thumb: "100x100>" }, default_url: "missingimage.png",
        storage: :s3,
        bucket: 'dsafricashop'
       # s3_credentials: "#{Rails.root}/config/application.yml"
        #path: "/:product/:style/:id/:filename"
        validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
        #product.image.url => 'https://dsafricashop.s3.amazonaws.com/'
#  end
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_presence :image
  belongs_to :user
  has_many :orders
  belongs_to :category
  belongs_to :color
  #has_many :order_items
  #to implement the product active status and show if true
  #default_scope { where(active: true) }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    if params[:category].blank?
      @products = Product.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 12)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: @category_id).order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
       # @order_item = current_order.order_items.new
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
def seller
  @products = Product.where(user: current_user).order('created_at DESC')
end
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :qtyperunit, :color_id, :image)
    end
  def check_user
    if current_user != @product.user
      redirect_to root_url, alert: "You cannot amend Products that belong ro another seller"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">

<%= form_for(@product, html: { multipart: true }) do |f| %>
  <% if @product.errors.any? %>
     <div id="error_explanation" class="alert alert-danger alert-dismissible">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="panel panel-info">
  <div class="panel-heading">Create || Edit Product</div>
  <div class="panel-body">
  <div class="form-group">
    <%= f.label :product_name %><br>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>
     <div class="form-group">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, {class: "btn btn-default dropdown-toggle"} %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control"  %>
  </div>
<!--   <div class="form-group">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :qtyperunit %><br>
    <%= f.text_field :qtyperunit, class: "form-control"  %>
  </div> -->
  <div class="form-group">
    <%= f.label :color_id %><br>
    <%= f.collection_select :color_id, Color.all, :id, :name, {prompt: "Select a color"}, {class: "btn btn-default dropdown-toggle"} %>
  </div>
 <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
 </div>

<% end %>
    </div>
 </div>
      <div class="col-md-2">
  </div>

app/views/products/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @product,class: "btn btn-link"  %> |
<%= link_to 'Back', products_path,class: "btn btn-link"  %>

app/views/products/index.html.erb
<div class="jumbotron">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="..." alt="First Image..">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="..." alt="Second Image...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    <h1>Made In Rwanda Products</h1>
    <h3>Explore african made items and save the continent</h3>
</div>
  <div class="center">
    <div class="row">
       <% @products.each do |product| %>
      <div class="col-md-3">
        <div class="thumbnail">
           <%= link_to image_tag(product.image.url(:medium)), product %>
            <div class="caption">
            <h3><%= link_to product.name, product,order_item: @order_items %></h3>
            <p><%= number_to_currency(product.price) %></p><br>
              <p><%= "Sold by #{product.user.name}" %></p><br>
                <p><%= link_to 'Add to cart', shopping_cart_path(:product_id => product), :method => 'POST', class:"btn btn-primary" %></p>

          </div>
          </div>
    </div>
<% end %>
</div>
  </div>
<br><br>

 <div align="right"><%= will_paginate @products, renderer: BootstrapPagination::Rails %></div>
<br>

 <% if (user_signed_in?) %>
    <%= link_to 'New Product', new_product_path, class: "btn btn-primary btn-sm active" %>
 <% end %>

app/views/products/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/seller.html.erb
 <% if (user_signed_in?) %>
    <%= link_to 'New Product', new_product_path, class: "btn btn-primary btn-sm active" %>
 <% end %>
<br>
<br>
<table class="table table-striped table-bordered">
<tr>
 <th>Image</th>
  <th>Name</th>
  <th>Description</th>
  <th>Price</th>
  <th>Action</th>
</tr>
 <% @products.each do |product| %>
<tr>
   <td> <%=  image_tag product.image.url(:thumb) %></td>
   <td><%= product.name %></td>
   <td><%= product.description %></td>
   <td><%= number_to_currency(product.price) %></td>
  <td> <div class="btn-group">
  <button type="button" class="btn btn-primary active">Action</button>
  <button type="button" class="btn btn-primary dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to 'View', product, class: "btn btn-link" %></li>
    <li><%= link_to 'Edit', edit_product_path(product), class: "btn btn-link" %></li>
    <li><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-link" %></li>
  </ul>
</div> <% end %></td>
</table>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-md-6">
      <div class="thumbnail">
      <%= image_tag @product.image.url %>
        </div>
    </div>

    <div class="col-md-6">
      <h3><%= @product.name %></h3>
      <p> <%= number_to_currency(@product.price) %></p>
      <p><%= @product.description %></p>
      <p><%= @product.color_id %></p>
      <p><%= @product.category_id %></p><br>
      <%= link_to "Buy Now", new_product_order_path(@product), class: "btn btn-primary active" %>
    </div>
  </div>

<% if current_user = @product.user && user_signed_in? %>
  <%= link_to 'Edit', edit_product_path(@product),class: "btn btn-btn-link" %> |
<% end %>

<%= link_to 'Back', products_path,class: "btn btn-btn-link"  %>